sudo: false
language: go
env:
    global:
      - GO111MODULE=on
      - GOPROXY=https://proxy.golang.org
      - HUGO_BUILD_TAGS=extended
git:
    depth: 1
go:
    - master
install: go get -v github.com/gohugoio/hugo
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $token
    on:
        branch: master
    local_dir: public
    repo: kangvcar/kangvcar.github.io
    fqdn: https://kangvcar.github.io
    target_branch: master
    email: kangvcar@126.com
    name: kangvcar
